import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, spacing, typography } from "@not-alone/design-tokens";

const awards = ["Bold Stand to Reduce Stigma", "Grassroots Leadership in Mental Health", "Legacy Advocacy and Transformation", "Music That Moved the World", "Film or Series Changing Perception", "Youth-Led Impact", "Clinical Excellence Award", "Scientific Breakthrough Award", "Technology for Humanity Award", "Philanthropy and Impact Award", "Creative Expression Award", "Lived Experience Award", "Legacy Award"];
const people2025 = ["Loni Love", "Jeneva Bell", "Alex Cohen", "John Couch", "Ellie Kanner", "Winston & Cameron Kelly", "Nick Kislinger", "Melony & Adam Lewis", "Rachel Platten", "Dr. George Rapier III", "Jennifer Smorgon", "Christopher Teas", "John Tyson", "Ryan Wolfington", "Sean & Ana Wolfington", "Janet & Steve Wozniak", "Flavor Flav"];
const removed2026 = new Set(["Rachel Platten", "Dr. George Rapier III", "Christopher Teas", "John Tyson", "Flavor Flav"]);

export default function AwardsScreen() {
  const [year, setYear] = useState<2025 | 2026>(2026);
  const people = year === 2026 ? people2025.filter((person) => !removed2026.has(person)) : people2025;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>Not Alone Awards</Text><Text style={styles.title}>Celebrating pioneers in human development & mental health.</Text><Text style={styles.copy}>Honoring leaders advancing emotional, social, and mental well-being through research, innovation, advocacy, philanthropy, and art.</Text><View style={styles.tabs}><Pressable style={[styles.tab,year===2026&&styles.active]} onPress={()=>setYear(2026)}><Text style={[styles.tabText,year===2026&&styles.activeText]}>2026</Text></Pressable><Pressable style={[styles.tab,year===2025&&styles.active]} onPress={()=>setYear(2025)}><Text style={[styles.tabText,year===2025&&styles.activeText]}>2025</Text></Pressable></View><Text style={styles.heading}>{year} Awards</Text><View style={styles.grid}>{awards.map((award)=><View style={styles.card} key={award}><Text style={styles.cardText}>{award}</Text></View>)}</View><Text style={styles.heading}>People</Text><View style={styles.people}>{people.map((person)=><Text style={styles.person} key={person}>{person}</Text>)}</View></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{backgroundColor:colors.canvas,flex:1},content:{padding:spacing.lg,paddingBottom:120},eyebrow:{color:colors.accent,fontFamily:typography.bold,fontSize:11,textTransform:"uppercase"},title:{color:colors.plum,fontFamily:typography.display,fontSize:34,lineHeight:39,marginTop:8},copy:{color:colors.body,fontSize:14,lineHeight:22,marginTop:12},tabs:{flexDirection:"row",gap:8,marginVertical:24},tab:{borderColor:colors.border,borderRadius:999,borderWidth:1,paddingHorizontal:20,paddingVertical:10},active:{backgroundColor:colors.plum},tabText:{color:colors.ink,fontFamily:typography.bold},activeText:{color:"white"},heading:{color:colors.plum,fontFamily:typography.display,fontSize:28,marginBottom:14,marginTop:24},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},card:{alignItems:"center",backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,justifyContent:"center",minHeight:100,padding:14,width:"48%"},cardText:{color:colors.ink,fontFamily:typography.semibold,fontSize:13,textAlign:"center"},people:{backgroundColor:colors.surface,borderRadius:10,padding:16},person:{borderBottomColor:colors.border,borderBottomWidth:1,color:colors.ink,fontFamily:typography.medium,paddingVertical:12}});
