packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.21'
  - '@expo/fingerprint@0.20.12'
  - '@expo/metro-runtime@57.0.15'
  - '@expo/router-server@57.0.9'
  - babel-preset-expo@57.0.10
  - expo-asset@57.0.16
  - expo-constants@57.0.17
  - expo-font@57.0.3
  - expo-modules-core@57.0.15
  - expo-modules-jsi@57.0.7
  - expo@57.0.19
  - '@expo/ui@57.0.15'
  - expo-dev-client@57.0.18
  - expo-dev-launcher@57.0.19
  - expo-dev-menu@57.0.18
  - expo-eas-client@57.0.3
  - expo-linking@57.0.9
  - expo-notifications@57.0.16
  - expo-router@57.0.18
  - expo-secure-store@57.0.3
  - expo-updates@57.0.21
overrides:
  "@react-native/metro-config": "0.86.3"
  "react-native-reanimated": "4.5.1"
