export const confirmedSummitGuests2026 = [
  "Jason Kennedy",
  "Loni Love",
  "Anthony Ramos",
  "Steve Wozniak",
  "Mike Majlak",
  "Kevin Hines",
  "Ryan Wolfington",
  "Jewel Murray",
  "Caroline Jones",
  "Nick Dana",
  "Sarah Steil",
  "Lexi Hensler",
  "Jon Hershfield",
  "Morgan Marler",
  "Nick Kislinger",
  "Sanem (Sam) Alkan",
  "Daniel Gillison",
  "Wendy Oliver-Pyatt",
  "Brandon Saho",
  "Michael Townsend",
  "Leah Smith",
  "Margaret Hines",
  "Caroline Silby",
  "Jessica Edwards",
  "Marc Brackett",
  "Ellie Kanner",
  "Kase Murray",
  "Trent Alenik",
  "Jan Thwaites",
  "Sally Dewhurst",
  "Sophie Novak",
  "Trevor Short",
  "Clark Cummings",
  "Aphrah Brokaw",
  "Paige Neuenschwander",
  "Noah Springer",
  "Melinda Springer",
  "Adam Lewis",
  "Melony Lewis",
  "Cameron Kelly",
  "Winston Kelly",
  "Jeneva Bell",
  "Alana Springsteen",
  "David Eagleman",
  "Bob Bryan",
  "Mike Bryan",
  "Blaise Aguirre",
  "Isabella Wolfington",
  "Steven Cohen",
  "Alexandra Cohen",
  "Jen Smorgen",
  "Sean Wolfington",
  "Ana Wolfington",
  "Janet Wozniak",
  "Cathy Olson"
] as const;

export const confirmedSummitGuests2026Source = {
  baseId: "app7BHptsc1bjc3DD",
  interfacePageId: "pagFmzDhXfNK53eWY",
  group: "Summit Status: Confirmed Attendance",
  reviewedAt: "2026-09-15",
  observedConfirmedRows: 59,
  publicConfirmedRows: 55,
  excludedRule: "Blank names and names explicitly marked TBC are withheld from public content.",
  accessMode: "Read-only Airtable interface review"
} as const;
