export const confirmedSummitGuests2026 = [
  "Jason Kennedy",
  "Loni Love",
  "Anthony Ramos",
  "Steve Wozniak",
  "Mike Majlak",
  "Kevin Hines",
  "Ryan Wolfington",
  "Jewel",
  "Caroline Jones",
  "Nick Dana",
  "Sarah Steil",
  "Lexi Hensler",
  "Jon Hershfield",
  "Morgan Marler",
  "Nick Kislinger",
  "Sanem (Sam) Alkan",
  "Daniel Gillison",
  "Wendy Oliver-Pyatt",
  "Brandon Saho",
  "Michael Townsend",
  "Leah Smith",
  "Margaret Hines",
  "Caroline Silby",
  "Jessica Edwards",
  "Marc Brackett",
  "Ellie Kanner",
  "Kase Murray",
  "Trent Alenik",
  "Jan Thwaites",
  "Sally Dewhurst",
  "Sophie Novak",
  "Trevor Short",
  "Clark Cummings",
  "Aphrah Brokaw",
  "Paige Neuenschwander",
  "Noah Springer",
  "Melinda Springer",
  "Alana Springsteen",
  "David Eagleman",
  "Bob Bryan",
  "Mike Bryan",
  "Blaise Aguirre",
  "Isabella Wolfington",
  "Steven Cohen",
  "Alexandra Cohen",
  "Jen Smorgen",
  "Sean Wolfington",
  "Ana Wolfington",
  "Janet Wozniak",
  "Cathy Olson",
  "Jeff Levin",
  "Darryl McDaniels (DMC)",
  "Mike Tyson"
] as const;

export const confirmedSummitGuests2026Source = {
  baseId: "app7BHptsc1bjc3DD",
  interfacePageId: "pagFmzDhXfNK53eWY",
  group: "Summit Status: Confirmed Attendance",
  reviewedAt: "2026-09-16",
  observedConfirmedRows: 56,
  publicConfirmedRows: 53,
  excludedRule: "Three TBC names withheld. Duplicate DMC record is no longer in the source; Darryl McDaniels (DMC) remains confirmed. Hold-space, invited, pending, and declined records excluded.",
  accessMode: "Read-only Airtable interface review"
} as const;
