export const confirmedSummitGuests2026 = [
  "Jason Kennedy",
  "Loni Love",
  "Anthony Ramos",
  "Steve Wozniak",
  "Mike Majlak",
  "Kevin Hines",
  "Ryan Wolfington",
  "Jewel Murray",
  "Erica McGraw",
  "Jay McGraw",
  "Caroline Jones",
  "Nick Dana",
  "Sarah Steil",
  "Lexi Hensler",
  "Jon Hershfield",
  "Morgan Marler",
  "Nick Kislinger",
  "Sanem Alkan",
  "Daniel Gillison",
  "Wendy Oliver-Pyatt",
  "Brandon Saho",
  "Michael Townsend",
  "Leah Smith",
  "Margaret Hines",
  "Caroline Silby",
  "Jessica Edwards",
  "Marc Brackett",
  "Ellie Kanner",
  "Kase Murray",
  "Trent Alenik",
  "Jan Thwaites",
  "Sally Dewhurst",
  "Sophie Novak",
  "Trevor Short",
  "Clark Cummings",
  "Aphrah Brokaw",
  "Paige Neuenschwander",
  "Noah Springer",
  "Melinda Springer",
  "Melony Lewis",
  "Cameron Kelly",
  "Jeneva Bell",
  "Alana Springsteen",
  "David Eagleman",
  "Bob Bryan",
  "Mike Bryan",
  "Blaise Aguirre",
  "Isabella Wolfington",
  "Raquelle Stevens",
  "Steven Cohen",
  "Alexandra Cohen",
  "Jen Smorgen",
  "Sean Wolfington",
  "Ana Wolfington"
] as const;

export const confirmedSummitGuests2026Source = {
  baseId: "app7BHptsc1bjc3DD",
  interfacePageId: "pagFmzDhXfNK53eWY",
  group: "Summit Status: Confirmed",
  reviewedAt: "2026-09-15",
  excludedRule: "Blank names and names explicitly marked TBC are withheld from public content."
} as const;
