import Link from "next/link";
import { awardCategories, awardsRoster, type AwardsYear } from "../lib/awards";
import { people2025, people2026 } from "../lib/people";

export function AwardsYearPage({ year }: { year: AwardsYear }) {
  const profiles = [...people2026, ...people2025];
  const roster = awardsRoster(year);
  return <main className="awardsPage"><section className="awardsHero"><p className="eyebrow">Invitation only · {year === 2026 ? "November 2, 2026" : "November 11, 2025"} · Wynn Las Vegas</p><h1>Not Alone Awards</h1><p>Celebrating the pioneers of human development and mental health—the visionaries, healers, and innovators who have broken barriers, challenged stigma, and illuminated a path toward healing, growth, and connection.</p><nav className="yearTabs" aria-label="Awards year"><Link className={year === 2026 ? "active" : ""} href="/awards/2026">2026 Awards</Link><Link className={year === 2025 ? "active" : ""} href="/awards/2025">2025 Awards</Link></nav></section><section className="awardsContent"><section className="awardsMission"><h2>Honoring those who invest in humanity.</h2><p>These awards recognize people advancing emotional, social, and mental well-being through research, clinical innovation, technology, advocacy, philanthropy, and art.</p></section><p className="noSolicitation"><strong>No Solicitation, Only Connection.</strong> We ask every guest to refrain from pitching, selling, or networking so our time can be devoted to authenticity, presence, and meaningful human connection.</p><section className="awardsSection"><p className="eyebrow">{year} Awards Show Host</p><h2>Hosted by Loni Love</h2><PersonCard name="Loni Love" role="Comedian & TV Host" image={profiles.find((person) => person.name === "Loni Love")?.image} featured /></section>{Object.entries(roster).map(([title, entries]) => <section className="awardsSection" key={title}><p className="eyebrow">{year} Not Alone Awards</p><h2>{title}</h2><div className="awardPeopleGrid">{entries.map((entry) => <PersonCard key={entry.name} {...entry} image={profiles.find((person) => person.name === entry.name)?.image} />)}</div></section>)}<section className="awardsSection"><p className="eyebrow">Why it matters</p><h2>Awards</h2><div className="awardGrid categoryAwardGrid">{awardCategories.map(([title, description]) => <article key={title}><div><strong>{title}</strong><p>{description}</p></div></article>)}</div></section><section className="awardsClosing"><p className="eyebrow">Celebrating pioneers</p><h2>Human development & mental health</h2><Link className="primaryButton" href="/#rsvp">RSVP for the {year} experience</Link></section></section></main>;
}

function PersonCard({ name, role, image, featured = false }: { name: string; role: string; image?: string | undefined; featured?: boolean }) {
  const content = <>{image ? <img src={image} alt={name} /> : <div className="awardInitials" aria-hidden="true">{name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</div>}<div><h3>{name}</h3><p>{role}</p></div></>;
  return featured ? <article className="hostFeature">{content}</article> : <article>{content}</article>;
}
